image: Ubuntu

stack: jdk 11

branches:
  only:
    - OrderCard

build: off

install:
  - java -jar ./artifacts/app-order.jar &
  -javaagent:/path/to/webdrivermanager.jar

build_script:
  - chmod +x gradlew
  - ./gradlew test --info